#!/usr/bin/env python3
"""Write the site's own SVGs and refresh the inline mark in the HTML pages.

    python3 tools/make_site_svgs.py

Writes logo.svg, logo-lockup.svg, favicon.svg, and rewrites whatever sits
between the `mark:start` / `mark:end` comments in each HTML page. Run it after
tools/design_mark.py, then run make_brand_assets.py and make_og.py.
"""

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from mark_geometry import (MARK_W, MARK_H, SKELETON_D, MASK_W, SOLID_BELOW_PX)
from markutil import (NAVY, COPPER, COPPER_ON_DARK, BADGE_FILL,
                      mark_bbox, mark_path, mark_svg)
import wordmark as wm

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HTML_PAGES = ("index.html", "404.html", "thanks.html")
START = "<!-- mark:start"
END = "<!-- mark:end -->"

# The header mark is 29 units of ink on a phone and 35 from 30em up, which
# straddles SOLID_BELOW_PX — so the circuit layer is switched off below that
# breakpoint in styles.css. Same artwork, one layer fewer.
HEADER_H = 29.0


def logo_svg():
    body = "\n".join(mark_svg(COPPER))
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {MARK_W} {MARK_H}" \
width="{MARK_W}" height="{MARK_H}" role="img" aria-labelledby="sac-logo-title">
  <title id="sac-logo-title">Southern AI Consulting</title>
  <!-- GENERATED by tools/make_site_svgs.py — edit tools/design_mark.py instead.

       An S built from one ellipse and its own 180-degree rotation, with a
       circuit trace running down the letter's own centreline.

       ONE PATH, ONE COLOUR. The circuit is a hole in the letter, not a second
       ink — even-odd fill, so whatever this sits on shows through the channel
       and the node rings. Nothing to recolour and nothing to keep in step.

       Below {SOLID_BELOW_PX} px of ink the channel closes up; use the letter on its own
       there (brand/logo-mark-solid-*.svg, or favicon.svg for a tab).

       Ink is tight to the box on all four sides. Apply clear space yourself:
       20% of the height, per brand/README.md. -->
{body}
</svg>
'''


def favicon_svg(size=64):
    s = BADGE_FILL * size / MARK_H
    ox, oy = (size - MARK_W * s) / 2, (size - MARK_H * s) / 2
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}" \
width="{size}" height="{size}" role="img" aria-labelledby="sac-favicon-title">
  <title id="sac-favicon-title">Southern AI Consulting</title>
  <!-- GENERATED by tools/make_site_svgs.py — edit tools/design_mark.py instead.

       Badge form: the mark reversed out of navy. A filled tile beats a bare
       letter in a browser tab, because the tab strip is a different colour in
       every theme and the mark keeps its own background either way.

       NO CIRCUIT LAYER here, deliberately. One SVG serves 16 px and 180 px
       alike and it cannot know which it is being drawn at; the binding case is
       the tab, where the trace closes into a smudge. This is the mark's
       reduction — the same drawing with one layer off, not a second artwork.

       One other difference from logo.svg: copper is lifted to {COPPER_ON_DARK},
       because the brand copper is only 1.9:1 on navy and goes muddy by 16px. -->
  <rect width="{size}" height="{size}" rx="{size * 0.22:.0f}" fill="{NAVY}"/>
  <g transform="translate({ox:.2f} {oy:.2f}) scale({s:.4f})">
{chr(10).join(mark_svg(COPPER_ON_DARK, circuit=False, indent="    "))}
  </g>
</svg>
'''


def lockup_svg():
    """Mark and wordmark side by side, laid out exactly like the print set.

    Same GAP, same LOCKUP_MARK_H, same TRACKING, and the same tight crop to the
    ink — all of it read from wordmark.py rather than restated here. It used to
    be restated, and drifted: this file drew the mark at its full 64 units
    while brand/logo-horizontal-* used 48, so the signature and the card showed
    two different logos.

    The one thing that is deliberately different is the type: live Georgia
    <text> here, real outlines there.
    """
    s = wm.LOCKUP_MARK_H / MARK_H
    dy = (MARK_H - wm.LOCKUP_MARK_H) / 2       # on the 64-unit centre line
    mx0, my0, mx1, my1 = mark_bbox()
    tx = mx1 * s + wm.GAP
    b1 = wm.text_bbox(tx, wm.BASE1, wm.LINE1)
    b2 = wm.text_bbox(tx, wm.BASE2, wm.LINE2)
    x0, y0 = mx0 * s, min(my0 * s + dy, b1[1], b2[1])
    x1, y1 = max(b1[2], b2[2]), max(my1 * s + dy, b1[3], b2[3])
    w, h = x1 - x0, y1 - y0
    body = "\n".join("  " + line for line in mark_svg(COPPER, indent=""))
    return f'''<svg xmlns="http://www.w3.org/2000/svg" \
viewBox="{x0:.3f} {y0:.3f} {w:.3f} {h:.3f}" \
width="{w:.3f}" height="{h:.3f}" role="img" aria-labelledby="sac-lockup-title">
  <title id="sac-lockup-title">Southern AI Consulting</title>
  <!-- GENERATED by tools/make_site_svgs.py — edit tools/design_mark.py instead.

       Horizontal lockup for email signatures, letterhead, and slides. Uses
       live Georgia text, which is ubiquitous on macOS and Windows but is NOT
       safe to hand a print vendor — a missing Georgia silently substitutes
       another face. For anything printed use brand/logo-horizontal-*.svg or
       .pdf, where the wordmark is real vector outlines. Geometry is otherwise
       identical to those files.

       Layout: {wm.LOCKUP_MARK_H:.0f} units of mark ink, centred on the wordmark's cap block,
       then {wm.GAP:.0f} units of air. Tight-cropped to the ink, so it drops into a
       layout already centred; apply clear space yourself. -->
  <g transform="translate(0 {dy:.3f}) scale({s:.5f})">
{body}
  </g>
  <g fill="{NAVY}" font-family="Georgia, 'Times New Roman', serif"
     font-size="{wm.TEXT_SIZE:.0f}" font-weight="700" letter-spacing="{wm.TRACKING}">
    <text x="{tx:.2f}" y="{wm.BASE1}">{wm.LINE1}</text>
    <text x="{tx:.2f}" y="{wm.BASE2}">{wm.LINE2}</text>
  </g>
</svg>
'''


def inline_mark(indent="      "):
    """The header mark, as inline SVG with the draw-on mask.

    The letter is a filled outline, so the old stroke-dashoffset trick has
    nothing to draw. Instead a fat stroke sweeps along the skeleton inside a
    mask, which reveals the artwork. Here the skeleton IS the letter's spine
    and the circuit trace is that same spine, so the sweep runs exactly down
    the channel: the mark draws itself the way current would run along it.
    pathLength="100" lets styles.css count 0-100 regardless of arc length.

    Because the circuit is a knockout rather than a painted channel, it needs
    nothing from the stylesheet: the page shows through it, in either theme,
    including through the header's own 92%-opaque backdrop as content scrolls
    under. That also means it cannot be switched off with CSS — a hole is not
    an element you can hide — so the two sizes ship as two paths and the
    stylesheet picks one. Below 30em the mark is 29 units of ink, under
    SOLID_BELOW_PX, and gets the letter alone.

    width/height are stated as attributes as well as in the stylesheet. They
    are the small-screen size, and CSS overrides them everywhere it loads —
    but 404.html and thanks.html reference /styles.css absolutely, so opening
    either straight off disk gets no stylesheet, and an SVG with only a
    viewBox would then scale to the full width of the page. fill= is set for
    the same reason: a presentation attribute loses to any stylesheet rule, so
    it only shows when there is no stylesheet at all.

    stroke-linecap="round" on the sweep is not optional: each end of the
    skeleton sits exactly on a terminal cut, and a butt cap would shave it.
    There are no square turns in this skeleton, so unlike the mark it replaces
    the join style does not matter.
    """
    return f'''{indent}{START} — generated by tools/make_site_svgs.py; edit tools/design_mark.py -->
{indent}<svg class="brand-mark" viewBox="0 0 {MARK_W} {MARK_H}" \
width="{MARK_W / MARK_H * HEADER_H:.1f}" height="{HEADER_H:.0f}"
{indent}     aria-hidden="true" focusable="false">
{indent}  <mask id="brand-draw" maskUnits="userSpaceOnUse"
{indent}        x="{-MASK_W:.2f}" y="{-MASK_W:.2f}" width="{MARK_W + 2 * MASK_W:.2f}" height="{MARK_H + 2 * MASK_W:.2f}">
{indent}    <path class="brand-sweep" pathLength="100" d="{SKELETON_D}"
{indent}          fill="none" stroke="#fff" stroke-width="{MASK_W}" stroke-linecap="round"/>
{indent}  </mask>
{indent}  <g mask="url(#brand-draw)">
{indent}    <path class="brand-letter brand-solid" d="{mark_path(False)}" fill="{COPPER}"/>
{indent}    <path class="brand-letter brand-full" d="{mark_path(True)}" fill-rule="evenodd" fill="{COPPER}" display="none"/>
{indent}  </g>
{indent}</svg>
{indent}{END}'''


def patch_html(path):
    src = open(path).read()
    m = re.search(re.escape(START) + r".*?" + re.escape(END), src, re.S)
    if not m:
        return f"{path}  SKIPPED — no mark:start/mark:end markers"
    indent = re.search(r"([ \t]*)" + re.escape(START), src).group(1)
    out = src[:m.start()] + inline_mark(indent).lstrip() + src[m.end():]
    if out != src:
        open(path, "w").write(out)
        return f"{path}  mark updated"
    return f"{path}  unchanged"


def main():
    for name, text in (("logo.svg", logo_svg()),
                       ("logo-lockup.svg", lockup_svg()),
                       ("favicon.svg", favicon_svg())):
        open(os.path.join(ROOT, name), "w").write(text)
        print(f"  {name}")
    for page in HTML_PAGES:
        print("  " + patch_html(os.path.join(ROOT, page)))


if __name__ == "__main__":
    main()
